// ΓöÇΓöÇΓöÇ Graph utility helpers ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

/** Resolve node id from either a plain string or a d3 resolved object. */
export function linkEndId(end) {
  return typeof end === "object" && end !== null ? end.id : end;
}


// ΓöÇΓöÇΓöÇ File / export helpers ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

export function downloadBlob(filename, content, mime) {
  const blob = new Blob([content], { type: mime });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}

export function graphToMarkdown(topic, summary, nodes, links) {
  const byId = new Map(nodes.map((n) => [n.id, n]));
  let md = `# ${topic}\n\n${summary || ""}\n\n## Concepts\n\n`;
  nodes
    .filter((n) => !n.isRoot)
    .forEach((n) => {
      md += `### ${n.label}\n- Category: ${n.category || "ΓÇö"}\n- Confidence: ${
        n.strength ? `${n.strength}/100` : "ΓÇö"
      }\n- ${n.explanation || ""}\n\n`;
    });
  md += `## Relationships\n\n`;
  links.forEach((l) => {
    const s = byId.get(linkEndId(l.source));
    const t = byId.get(linkEndId(l.target));
    if (!s || !t) return;
    md += `- **${s.label}** ΓåÆ **${t.label}** (${l.relationship || "related"}, confidence ${l.strength || "ΓÇö"})\n`;
  });
  md += `\n---\n*Generated by NeuroWeb.*\n`;
  return md;
}

export function svgToPngDownload(svgEl, filename, bgColor = "#05060a") {
  const serializer = new XMLSerializer();
  const clone      = svgEl.cloneNode(true);
  const rect       = svgEl.getBoundingClientRect();
  clone.setAttribute("width",  rect.width);
  clone.setAttribute("height", rect.height);
  const svgStr = serializer.serializeToString(clone);
  const svgBlob = new Blob([svgStr], { type: "image/svg+xml;charset=utf-8" });
  const url  = URL.createObjectURL(svgBlob);
  const img  = new Image();
  img.onload = () => {
    const canvas = document.createElement("canvas");
    const scale  = 2;
    canvas.width  = rect.width  * scale;
    canvas.height = rect.height * scale;
    const ctx = canvas.getContext("2d");
    ctx.fillStyle = bgColor;
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    ctx.scale(scale, scale);
    ctx.drawImage(img, 0, 0, rect.width, rect.height);
    URL.revokeObjectURL(url);
    canvas.toBlob((blob) => {
      const a    = document.createElement("a");
      a.href     = URL.createObjectURL(blob);
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      a.remove();
    }, "image/png");
  };
  img.src = url;
}

/** Case-insensitive substring match used for command palette filtering. */
export function fuzzyMatch(query, text) {
  if (!query) return true;
  return text.toLowerCase().includes(query.toLowerCase());
}
